"""initial_schema

Revision ID: a22b27560724
Revises:
Create Date: 2026-08-04 15:09:16.166454

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "a22b27560724"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
